using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MercedesCarController : MonoBehaviour {

    private const string Horizontal = "Horizontal";
    private const string Vertical = "Vertical";


    private float DirHorizontal;
    private float DirVertical;
    private float steerAngle;

    public WheelCollider WheelCFR, WheelCFL, WheelCBR, WheelCBL;
    public Transform WheelTFR, WheelTFL, WheelTBR, WheelTBL;
    public float maxSteerAngle = 30;
    public float motorForce = 300;
    public float brakes = 0;

    public void DirectionsInput()
    {
        DirHorizontal = Input.GetAxis("Horizontal");
        DirVertical = Input.GetAxis("Vertical");
    }

    public void steerControl()
    {
        steerAngle = maxSteerAngle * DirHorizontal;
        WheelCFR.steerAngle = steerAngle;
        WheelCFL.steerAngle = steerAngle;
    }

    public void speedControl()
    {
        if (DirVertical == 0 || Input.GetKey(KeyCode.Space))
        {
            brakes = 300;
        }
        else
        {
            brakes = 0;
            WheelCFR.motorTorque = DirVertical * motorForce;
            WheelCFL.motorTorque = DirVertical * motorForce;
            WheelCBR.motorTorque = DirVertical * motorForce;
            WheelCBL.motorTorque = DirVertical * motorForce;
        }

        WheelCFR.brakeTorque = brakes;
        WheelCFL.brakeTorque = brakes;
        WheelCBR.brakeTorque = brakes;
        WheelCBL.brakeTorque = brakes;
    }

    public void wheelPositionControl()
    {
        wheelPositionControls(WheelCFR, WheelTFR);
        wheelPositionControls(WheelCFL, WheelTFL);
        wheelPositionControls(WheelCBR, WheelTBR);
        wheelPositionControls(WheelCBL, WheelTBL);
    }

    public void wheelPositionControls(WheelCollider collide, Transform trans)
    {
        Vector3 wheelPosition = trans.position;
        Quaternion wheelQuant = trans.rotation;

        collide.GetWorldPose(out wheelPosition, out wheelQuant);

        trans.position = wheelPosition;
        trans.rotation = wheelQuant;
    }

    public void FixedUpdate()
    {
        DirectionsInput();
        steerControl();
        speedControl();
        wheelPositionControl();
    }

    // Use this for initialization
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }
}
